name: MasterPipeline

on:
  push:
    branches: [ 'master' ]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java & Maven
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          maven: '3.6.3'

      - name: Maven Build
        run: mvn -B clean package -Dmaven.test.skip=true

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BUILD_ARTIFACT_LINUX
          path: server/target/kkFileView-*.tar.gz

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BUILD_ARTIFACT_WINDOWS
          path: server/target/kkFileView-*.zip
